"use client";

import Link from "next/link";
import { ArrowRight, ArrowLeft } from "lucide-react";
import {
  ChapterHeader,
  RevealSection,
  RevealItem,
  InsightCallout,
  SectionDivider,
  ProcessFlow,
  KPICard,
} from "@/components/Animated";

export default function GoToMarket() {
  return (
    <article className="prose-wp">
      <ChapterHeader
        chapter="Chapter 11"
        title="Go-to-Market Strategy"
        subtitle="From Cold Start to Critical Mass: Humanity-Led Growth"
        readTime="7 min read"
      />

      <RevealSection>
        <RevealItem>
          <InsightCallout source="Andrew Chen, &ldquo;The Cold Start Problem,&rdquo; 2022">
            The hardest part of building a network effect business is getting the first side of the
            marketplace to show up. twin3 solves this with a 300,000-user warm start.
          </InsightCallout>
        </RevealItem>

        <RevealItem>
          <h2>11.1 Warm-Start Advantage</h2>
        </RevealItem>
        <RevealItem>
          <p>
            twin3 is not launching into a vacuum. The founding team operates an existing Web2
            platform with <strong className="text-cream">300,000+ active users</strong> — a
            ready-made community that can be migrated to the twin3 ecosystem with near-zero CAC.
          </p>
        </RevealItem>
      </RevealSection>

      <SectionDivider label="HUMANITY-LED GROWTH" />

      <RevealSection>
        <RevealItem>
          <h2>11.2 Humanity-Led Growth</h2>
        </RevealItem>
        <RevealItem>
          <p>
            twin3&apos;s growth engine is powered by{" "}
            <strong className="text-cream">Proof-of-Humanity</strong> integration. By offering
            a free, open, permissionless humanity verification infrastructure (
            <a href="https://humanity.twin3.ai" target="_blank" rel="noopener noreferrer">
              humanity.twin3.ai
            </a>
            ), twin3 embeds itself into the trust layer of every app, dApp, community bot, and
            website that integrates its SDK.
          </p>
        </RevealItem>

        <RevealItem>
          <div className="glass-panel rounded-lg p-6 my-6">
            <p className="mono-label text-[0.5rem] text-cream-soft/30 mb-4">INTEGRATION CHANNELS</p>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
              {[
                { channel: "Website SDK", desc: "2 lines of HTML", detail: "Zero-config, no API key" },
                { channel: "REST API", desc: "Query verification", detail: "Protected endpoints" },
                { channel: "Telegram Bot", desc: "Auto-verify members", detail: "Group protection" },
                { channel: "Discord Bot", desc: "Verified role assign", detail: "Server protection" },
                { channel: "AI Agent Skill", desc: "OpenClaw compatible", detail: "Agent-native" },
                { channel: "On-Chain", desc: "Permissionless query", detail: "Smart contract read" },
              ].map((c, i) => (
                <div key={i} className="glass-panel rounded-lg p-3 text-center">
                  <h4 className="font-heading text-cream text-[0.72rem] !mt-0 !mb-0.5">{c.channel}</h4>
                  <p className="text-[0.6rem] text-cream-soft/50 !mb-0">{c.desc}</p>
                  <p className="text-[0.5rem] text-sage/50 !mb-0">{c.detail}</p>
                </div>
              ))}
            </div>
          </div>
        </RevealItem>

        <RevealItem>
          <p>
            Every integration source tracks referrals via first-touch attribution. Communities that
            install twin3 verification (e.g., Telegram bot) receive{" "}
            <strong className="text-cream">10% revenue share</strong> of the twin3 economic
            earnings generated by members they onboard. This creates a viral, self-reinforcing
            distribution loop:
          </p>
        </RevealItem>

        <RevealItem>
          <div className="glass-panel rounded-lg p-5 my-6 border-l-2 border-gold/40">
            <p className="text-[0.78rem] text-cream-soft/60 !mb-0">
              Community installs bot → Members verify → Members earn in twin3 economy →
              Community receives 10% of member earnings → Community promotes more → Network grows
            </p>
          </div>
        </RevealItem>
      </RevealSection>

      <SectionDivider label="OPEN MATRIX SDK" />

      <RevealSection>
        <RevealItem>
          <h2>11.3 Open Matrix SDK Ecosystem</h2>
        </RevealItem>
        <RevealItem>
          <p>
            twin3 opens the Twin Matrix as a shared infrastructure layer through two complementary
            SDKs, enabling a thriving ecosystem of applications built on human identity data:
          </p>
        </RevealItem>

        <RevealItem>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
            <div className="glass-panel rounded-lg p-5 border-t-2 border-sage/40">
              <span className="mono-label text-[0.5rem] text-sage block mb-2">MATRIX (READ)</span>
              <h4 className="font-heading text-cream text-base !mt-0 !mb-2">Read SDK</h4>
              <p className="text-[0.78rem] text-cream-soft/60 !mb-0">
                Third-party apps, dApps, and AI agents can read specific Twin Matrix dimensions
                (with user consent). Use cases: personalized recommendations, targeted matching,
                filtered access, reputation checks.
              </p>
            </div>

            <div className="glass-panel rounded-lg p-5 border-t-2 border-gold/40">
              <span className="mono-label text-[0.5rem] text-gold block mb-2">MATRIX (WRITE)</span>
              <h4 className="font-heading text-cream text-base !mt-0 !mb-2">Write SDK</h4>
              <p className="text-[0.78rem] text-cream-soft/60 !mb-0">
                Ecosystem partners can issue specialized SBTs, write verification results, and
                contribute new credentials to user profiles. Use cases: skill badges, course
                completions, health records, community roles.
              </p>
            </div>
          </div>
        </RevealItem>

        <RevealItem>
          <p>
            The Matrix SDK is the primary use case for the{" "}
            <strong className="text-cream">Ecosystem Growth pool</strong> (15% of total supply) —
            developer grants, hackathons, and integration bounties all drive adoption of the Read
            and Write SDKs across web, mobile, dApp, and agent ecosystems.
          </p>
        </RevealItem>
      </RevealSection>

      <SectionDivider label="THREE PHASES" />

      <RevealSection>
        <RevealItem>
          <h2>11.4 Launch Phases</h2>
        </RevealItem>
        <RevealItem>
          <ProcessFlow
            steps={[
              { label: "Phase 1 — Seed", description: "Migrate 300K warm-start users. Mint initial SBTs. Deploy core HaaS marketplace. Humanity-Led Growth via SDK integration. Target: 100K on-chain SBTs." },
              { label: "Phase 2 — Scale", description: "Enterprise partnerships. Matrix SDK (Read/Write) distribution. Community referral program at scale. Target: 500K SBTs, $5M+ ARR." },
              { label: "Phase 3 — Network", description: "Agent-to-Agent economy. Decentralized governance. Cross-chain expansion. Target: 1.5M+ SBTs, protocol-level revenue." },
            ]}
          />
        </RevealItem>
      </RevealSection>

      <SectionDivider label="KEY METRICS" />

      <RevealSection className="grid grid-cols-2 lg:grid-cols-4 gap-3 my-8">
        <RevealItem><KPICard label="Warm Start" value={300000} prefix="" note="Active users" accentColor="gold" /></RevealItem>
        <RevealItem><KPICard label="Current SBTs" value={141357} prefix="" note="BNB Chain" accentColor="cream" /></RevealItem>
        <RevealItem><KPICard label="Year 1 Target" value={100000} prefix="" note="On-chain SBTs" accentColor="sage" /></RevealItem>
        <RevealItem><KPICard label="Year 2 ARR" value={5} prefix="$" suffix="M+" note="Enterprise revenue" accentColor="gold" /></RevealItem>
      </RevealSection>

      <SectionDivider />

      <div className="flex flex-col sm:flex-row justify-between gap-4 pt-4">
        <Link href="/investment"><button className="btn-outline px-5 py-2.5 text-sm flex items-center gap-2"><ArrowLeft className="w-4 h-4" /> Investment</button></Link>
        <Link href="/roadmap"><button className="btn-gold px-5 py-2.5 text-sm flex items-center gap-2">Next: Development Roadmap <ArrowRight className="w-4 h-4" /></button></Link>
      </div>
    </article>
  );
}
